---

- name: login to docker registry
  community.docker.docker_login:
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
    registry: "{{ registry }}"
    reauthorize: yes
  when: registry != ""

- name: init deploy root
  community.general.deploy_helper:
    path: "{{ app_root }}"
    release: "{{ app_version }}"

- name: show variables
  debug:
    msg: |
      - app_root: {{ app_root }}
      - app_version: {{ app_version }}
      - templates_folder: {{ templates_folder }}
      - current_path: {{ deploy_helper.current_path }}


- name: deploy and up app with docker-compose
  block:
    - name: create release directory
      file:
        dest: "{{ deploy_helper.new_release_path }}"
        state: directory
        mode: 0775

    - name: create files from templates
      template:
        src:  "{{ item }}"
        dest: "{{ deploy_helper.new_release_path }}/{{ item | basename | regex_replace('\\.j2$','') }}"
        mode: 0775
      with_fileglob:
        - "{{ templates_folder }}/*.j2"

    - name: check docker-compose.yml from previous version
      stat:
        path: "{{ deploy_helper.current_path }}/docker-compose.yml"
      register: old_docker_compose_yml

    - name: stop existing services from previous version
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ deploy_helper.previous_release_path }}"
        stopped: yes
      when: old_docker_compose_yml.stat.exists

    - name: create and start services
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ deploy_helper.new_release_path }}"
        build: false
        pull: true
      register: output

    - ansible.builtin.debug:
        var: output

    - community.general.deploy_helper:
        path: "{{ app_root }}"
        release: "{{ app_version }}"
        state: finalize
        keep_releases: "{{ app_keep_releases }}"

  when: state == "present" and app_root != "" and app_version != "" and templates_folder != ""


# stop services by docker-compose block
- name: stop app with docker-compose
  block:
    - name: down existing services
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ deploy_helper.previous_release_path }}"
        stopped: yes

  when: state == "stopped" and app_root != "" and app_version != ""


# WARN: absent remove all data!!
- name: absent app
  block:
    - name: down existing services
      community.docker.docker_compose:
        project_name: "{{ project_name }}"
        project_src: "{{ deploy_helper.previous_release_path }}"
        stopped: yes
        state: absent

    - name: remove {{ app_root }}
      community.general.deploy_helper:
        path: "{{ app_root }}"
        state: absent

  when: state == "absent" and app_root != "" and app_version != ""


- name: logout from docker registry
  community.docker.docker_login:
    state: absent
  when: registry != ""
...
